url: "https://crandmck.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/jekyll-demo" # the subpath of your site, e.g. /blog
title: "Jekyll demos by Rand" # the name of your site, e.g. ACME Corp.
